--- arch/arm64/boot/dts/allwinner/overlay/Makefile
+++ arch/arm64/boot/dts/allwinner/overlay/Makefile
@@ -49,6 +49,10 @@ dtb-$(CONFIG_ARCH_SUNXI) += \
 	sun50i-h6-uart2.dtbo \
 	sun50i-h6-uart3.dtbo \
 	sun50i-h6-w1-gpio.dtbo \
+	sun50i-h616-gpu.dtbo \
+	sun50i-h616-i2c0-pi.dtbo \
+	sun50i-h616-i2c1-pi.dtbo \
+	sun50i-h616-i2c2-pi.dtbo \
 	sun50i-h616-i2c2-ph.dtbo \
 	sun50i-h616-i2c3-pg.dtbo \
 	sun50i-h616-i2c3-ph.dtbo \
